"""
src/report/generator.py
Generates exportable clinical review reports in Markdown and plain text format
from an ExtractionResult. Reports are labeled as prototype outputs only.
"""

from datetime import datetime


def _header(title: str, char: str = "=") -> str:
    return f"{title}\n{char * len(title)}"


def generate_markdown(result_dict: dict, document_name: str = "Clinical Document") -> str:
    """
    Generate a Markdown-formatted clinical review report.

    Args:
        result_dict: ExtractionResult.to_dict() output.
        document_name: Display name for the source document.

    Returns:
        Markdown string ready to download or display.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = []

    lines.append("# ClinicalAI Insight — Review Report")
    lines.append(f"\n> **Prototype output for demonstration only. Not for clinical or billing use.**\n")
    lines.append(f"**Document:** {document_name}  ")
    lines.append(f"**Generated:** {now}  ")

    conf = result_dict.get("overall_confidence", 0)
    lines.append(f"**Overall Confidence:** {int(conf * 100)}%\n")
    lines.append("---\n")

    # Patient
    p = result_dict.get("patient", {})
    lines.append("## Patient Demographics\n")
    lines.append(f"| Field | Value |")
    lines.append(f"|---|---|")
    lines.append(f"| Age | {p.get('age') or 'N/A'} |")
    lines.append(f"| Sex | {p.get('sex') or 'N/A'} |")
    lines.append(f"| DOB | {p.get('dob') or 'N/A'} |")
    lines.append(f"| MRN | {p.get('mrn') or 'N/A'} |\n")

    # Summary
    summary = result_dict.get("clinical_summary", "")
    if summary:
        lines.append("## Clinical Summary\n")
        lines.append(f"{summary}\n")

    # Diagnoses
    diagnoses = result_dict.get("diagnoses", [])
    if diagnoses:
        lines.append("## Diagnoses\n")
        lines.append("| Diagnosis | ICD-10 | Type | Confidence |")
        lines.append("|---|---|---|---|")
        for dx in diagnoses:
            icd = dx.get("icd10") or "N/A"
            conf_pct = f"{int(float(dx.get('confidence', 0.9)) * 100)}%"
            lines.append(f"| {dx['name']} | `{icd}` | {dx.get('type','').upper()} | {conf_pct} |")
        lines.append("")

        lines.append("### Evidence\n")
        for dx in diagnoses:
            ev = dx.get("evidence", "")
            if ev:
                lines.append(f"**{dx['name']}:** *\"{ev}\"*\n")

    # Medications
    medications = result_dict.get("medications", [])
    if medications:
        lines.append("## Medications\n")
        lines.append("| Medication | Dose | Route | Frequency | Status |")
        lines.append("|---|---|---|---|---|")
        for med in medications:
            lines.append(
                f"| {med['name']} "
                f"| {med.get('dose') or ''} "
                f"| {med.get('route') or ''} "
                f"| {med.get('frequency') or ''} "
                f"| {med.get('status','').upper()} |"
            )
        lines.append("")

    # Procedures
    procedures = result_dict.get("procedures", [])
    if procedures:
        lines.append("## Procedures\n")
        lines.append("| Procedure | CPT Code | Confidence |")
        lines.append("|---|---|---|")
        for proc in procedures:
            cpt = proc.get("cpt") or "N/A"
            conf_pct = f"{int(float(proc.get('confidence', 0.9)) * 100)}%"
            lines.append(f"| {proc['name']} | `{cpt}` | {conf_pct} |")
        lines.append("")

    # Payment Integrity
    pi = result_dict.get("payment_integrity", {})
    lines.append("## Payment Integrity Review\n")

    def status_icon(val): return "YES" if val else "NO"

    lines.append(f"| Check | Status |")
    lines.append(f"|---|---|")
    lines.append(f"| Diagnoses Documented | {status_icon(pi.get('diagnoses_documented', True))} |")
    lines.append(f"| Procedures Documented | {status_icon(pi.get('procedures_documented', True))} |")
    lines.append(f"| Medications Documented | {status_icon(pi.get('medications_documented', True))} |")
    lines.append("")

    flags = pi.get("flags", [])
    if flags:
        lines.append("### Flags\n")
        for flag in flags:
            lines.append(f"- {flag}")
        lines.append("")

    obs = pi.get("observations", "")
    if obs:
        lines.append(f"### Observations\n\n{obs}\n")

    lines.append("---")
    lines.append("\n> *This report was generated by ClinicalAI Insight, a proof-of-concept prototype "
                 "built for the Cotiviti Intern Assessment. All outputs are AI-generated illustrations "
                 "and must not be used for clinical, billing, or payment integrity decisions.*")

    return "\n".join(lines)


def generate_plain_text(result_dict: dict, document_name: str = "Clinical Document") -> str:
    """
    Generate a plain-text formatted clinical review report.

    Args:
        result_dict: ExtractionResult.to_dict() output.
        document_name: Display name for the source document.

    Returns:
        Plain text report string.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M")
    lines = []

    lines.append("CLINICALAI INSIGHT - REVIEW REPORT")
    lines.append("PROTOTYPE OUTPUT - NOT FOR CLINICAL OR BILLING USE")
    lines.append("=" * 60)
    lines.append(f"Document : {document_name}")
    lines.append(f"Generated: {now}")
    conf = result_dict.get("overall_confidence", 0)
    lines.append(f"Confidence: {int(conf * 100)}%")
    lines.append("=" * 60)

    summary = result_dict.get("clinical_summary", "")
    if summary:
        lines.append("\nCLINICAL SUMMARY")
        lines.append("-" * 40)
        lines.append(summary)

    diagnoses = result_dict.get("diagnoses", [])
    if diagnoses:
        lines.append("\nDIAGNOSES")
        lines.append("-" * 40)
        for dx in diagnoses:
            icd = dx.get("icd10") or "N/A"
            tag = dx.get("type","").upper()
            lines.append(f"  [{tag}] {dx['name']}  (ICD-10: {icd})")
            ev = dx.get("evidence","")
            if ev:
                lines.append(f"    Evidence: \"{ev}\"")

    medications = result_dict.get("medications", [])
    if medications:
        lines.append("\nMEDICATIONS")
        lines.append("-" * 40)
        for med in medications:
            parts = [med["name"]]
            if med.get("dose"): parts.append(med["dose"])
            if med.get("route"): parts.append(med["route"])
            if med.get("frequency"): parts.append(med["frequency"])
            lines.append(f"  [{med.get('status','').upper()}] {' | '.join(parts)}")

    procedures = result_dict.get("procedures", [])
    if procedures:
        lines.append("\nPROCEDURES")
        lines.append("-" * 40)
        for proc in procedures:
            cpt = proc.get("cpt") or "N/A"
            lines.append(f"  {proc['name']}  (CPT: {cpt})")

    pi = result_dict.get("payment_integrity", {})
    lines.append("\nPAYMENT INTEGRITY REVIEW")
    lines.append("-" * 40)
    lines.append(f"  Diagnoses Documented : {'YES' if pi.get('diagnoses_documented') else 'NO'}")
    lines.append(f"  Procedures Documented: {'YES' if pi.get('procedures_documented') else 'NO'}")
    lines.append(f"  Medications Documented: {'YES' if pi.get('medications_documented') else 'NO'}")

    flags = pi.get("flags", [])
    if flags:
        lines.append("\n  Flags:")
        for flag in flags:
            lines.append(f"    - {flag}")

    obs = pi.get("observations","")
    if obs:
        lines.append(f"\n  Observations: {obs}")

    lines.append("\n" + "=" * 60)
    lines.append("END OF REPORT - PROTOTYPE ONLY")

    return "\n".join(lines)
